### ISSUE TITLE
Change some KW mappings (term obsoletions) 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4234]
Hi @Antonialock 

Would you please change the following KW mappings: 

- [x] KW-1086 maps to [GO:0039553 suppression by virus of host chemokine activity](https://github.com/geneontology/go-ontology/issues/23655), please change to  GO:0042785 evasion of host immune response via regulation of host cytokine network
- [x] KW:KW-1085 maps to [GO:0019050 suppression by virus of host apoptotic process](https://github.com/geneontology/go-ontology/issues/23652), please change to  GO:0019050 suppression by virus of host apoptotic process
- [x] KW-1110 Inhibition of host TRAFs by virus > maps to [GO:0039547 suppression by virus of host TRAF activity ](https://github.com/geneontology/go-ontology/issues/23644); please move to GO:0039527 suppression by virus of host TRAF-mediated signal transduction 
- [x] KW-1075 Inhibition of host translation factors by virus: change to GO:0039606 suppression by virus of host translation initiation

**Comment by Antonialock** [comment]
Fixed
