### ISSUE TITLE
Review annotations to some tRNA modification terms that are duplicate of other terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-annotation#4740]
Dear all, 

The proposal has been made to obsolete 

- [x] GO:0103048 tRNA m2A37 methyltransferase activity  (see https://github.com/geneontology/go-ontology/issues/26114) 
- [x] GO:0097697 tRNA 5-carboxymethoxyuridine methyltransferase activity (https://github.com/geneontology/go-ontology/issues/26117)
- [x] GO:0030696 tRNA (m5U54) methyltransferase activity (https://github.com/geneontology/go-ontology/issues/26118)
- [x] GO:0030698 5,10-methylenetetrahydrofolate-dependent tRNA (m5U54) methyltransferase activity (https://github.com/geneontology/go-ontology/issues/26118)

Annotations are here: 
https://docs.google.com/spreadsheets/d/1ab7y7fBJCOE5o47fWnhcUKgbizQ6PUD5WW5Td36zE-Y/edit#gid=0

2 SGD 
1 EcoCyc

Mappings: 

- [ ] UniRule:UR000100529 > GO:0030698 GO:5,10-methylenetetrahydrofolate-dependent tRNA (m5U54) methyltransferase activity >>> ~change to GO:0030697 S-adenosylmethionine-dependent tRNA (m5U54) methyltransferase activity~ change to GO:0047151 'tRNA (uracil(54)-C-(5))-methyltransferase activity, 5,10-methylenetetrahydrofolate-dependent'
- [ ] HAMAP:MF_01037 > GO:0030698 GO:5,10-methylenetetrahydrofolate-dependent tRNA (m5U54) methyltransferase activity >>> ~change to GO:0030697 S-adenosylmethionine-dependent tRNA (m5U54) methyltransferase activity~ change to GO:0047151 'tRNA (uracil(54)-C-(5))-methyltransferase activity, 5,10-methylenetetrahydrofolate-dependent'
- [ ] ~UniRule:UR000293356 > GO:0097697 GO:tRNA 5-carboxymethoxyuridine methyltransferase activity >> change to     GO:0106335 tRNA (carboxymethyluridine(34)-5-O)-methyltransferase activity~
- [ ] ~HAMAP:MF_02057 > GO:0097697 GO:tRNA 5-carboxymethoxyuridine methyltransferase activity >> change to     GO:0106335 tRNA (carboxymethyluridine(34)-5-O)-methyltransferase activity~

Thanks.

**Comment by amandamackie** [comment]
EcoCyc done

**Comment by pgaudet** [comment]
@amandamackie I apologize, your annotation to GO:0097697 | tRNA 5-carboxymethoxyuridine methyltransferase activity
was right (I was thrown off by inconsistencies between term labels and definitions) 

The 2 activities are very similar, but RHEA:54080/GO:0097697 uses 5-carboxymethoxyuridine34 as substrate, while [RHEA:43208](https://www.rhea-db.org/rhea/43208)/GO:0106335 uses 5-carboxymethoxyuridine34. 

Sorry about that.

**Comment by pgaudet** [comment]
@srengel I am afraid the annotation need to be reviewed, since I found 2 different more specific terms. The correct term for the yeast activity is in the spreadsheet.

**Comment by amandamackie** [comment]
No problem, I should have looked more carefully too. I've reverted the change now

**Comment by pgaudet** [comment]
Thanks !

**Comment by srengel** [comment]
SGD done.
